name: Deploy Firebase Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions-Abhängigkeiten
        working-directory: functions
        run: npm install

      - name: Lint Functions
        working-directory: functions
        run: npm run lint

      - name: Authentifiziere Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Firebase Deploy
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only firestore:rules,functions --project "$FIREBASE_PROJECT_ID"
